### ISSUE TITLE
details.html - Dates display poorly when contact is first created

### ISSUE THREAD

**Issue by rutherling** [rutherling/201finalProject#133]
"invalid date" problem. Is it adding the days OK?

**Comment by GeoffreyEmerson** [comment]
I'll make that prettier. When you add a new contact, there is no "last contacted" date. Unless we want to assume today.

**Comment by rutherling** [comment]
ok. i was worried because the one I added didn't go to the timeline.

**Comment by GeoffreyEmerson** [comment]
fixed by somebody else. Maybe Charles.
