### ISSUE TITLE
overdue.html - empty page should redirect user to timeline

### ISSUE THREAD

**Issue by GeoffreyEmerson** [rutherling/201finalProject#141]

**Comment by CharlesEmrich** [comment]
I want to to discuss a failed fix to this issue because I suspect my failure is interesting, but this is a non-issue: if there are no overdue people, there is ipso facto no link to overdue.html.

**Comment by GeoffreyEmerson** [comment]
Completed. This was for when you processed overdue contacts on the overdue page.
