### ISSUE TITLE
form.html no longer writes to localStorage

### ISSUE THREAD

**Issue by rutherling** [rutherling/201finalProject#58]
When I submit a filled out contact from form.html, it should go to localStorage, but it doesn't.

**Comment by rutherling** [comment]
I need this so I can test the tagline on the bubble (and get the sizing right). None of the demo data has taglines, and my test isn't working.
I think it's because we changed a variable to details.prop? Or not both the demo data and new data can populate contactArray??

**Comment by rutherling** [comment]
the id makes it to contactArray, but object details get lost somewhere.

**Comment by GeoffreyEmerson** [comment]
fixed
